accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import list_view, show_project, create_project

urlpatterns = [
    path("", list_view, name="list_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path("create/", create_project, name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import create_task, my_tasks, update_task_status

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", my_tasks, name="show_my_tasks"),
    path("update-task-status/", update_task_status, name="update_task_status"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    re_path(
        r"^$",
        RedirectView.as_view(url="/projects/", permanent=False),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    # add account and tasks urls here later
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(default=timezone.now)
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput, max_length=150)


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput, max_length=150)
    password_confirmation = forms.CharField(
        widget=forms.PasswordInput, max_length=150
    )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password != password_confirmation:
            raise ValidationError("The passwords do not match")

        return cleaned_data

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ["is_completed"]

accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, SignUpForm


# Create your views here.
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                return redirect("list_projects")
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("login")


def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]
            if password == password_confirmation:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                return redirect("list_projects")
            else:
                form.add_error("password_confirmation", "Passwords must match")
    else:
        form = SignUpForm()
    context = {"form": form}
    return render(request, "registration/signup.html", context)


# In my view, and according to some.  The future of coding and technical literacy may
# be as important as literacy is today.  In 2020 MIT neuroscientist found that interpreting code
# activates a general-purpose brain network, but not language-processing centers.
# either way the best way to learn is practice!

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project
from .forms import ProjectForm


@login_required
def list_view(request):
    projects = Project.objects.filter(owner=request.user)
    if not projects:
        message = "You are not assigned to any projects"
    else:
        message = None
    context = {
        "projects": projects,
    }
    return render(request, "projects/list_projects.html", context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, id=id, owner=request.user)
    context = {
        "project": project,
    }
    return render(request, "projects/project_details.html", context)


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm()
    context = {
        "form": form,
    }
    return render(request, "projects/create_project.html", context)


# In my view.  Single quotes is easier to use because you
# dont have to shift.  Exept when it comes to other languages.
# It might be an issue.  I don't know enough to be sure.  Oh well!

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import TaskForm
from .models import Task


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = TaskForm()
    return render(request, "tasks/create_task.html", {"form": form})


@login_required
def my_tasks(request):
    tasks = Task.objects.filter(assignee=request.user)
    if not tasks:
        message = "You are not assigned to any projects"
    else:
        message = None
    return render(request, "tasks/my_tasks.html", {"tasks": tasks})


@require_POST
def update_task_status(request):
    for key in request.POST:
        if key.startswith("task_completed_"):
            task_id = key.split("_")[2]
            task = Task.objects.get(id=task_id)
            task.is_completed = key in request.POST
            task.save()
    return redirect("show_my_tasks")


# In my view.  The greatest super power would be hydrokinesis.
# It is universal.  It is life.

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div class="login-form">
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
           <div>
              <label for="id_username">Username:</label>
              <input type="text" name="username" id="id_username" required>
           </div>
           <div>
              <label for="id_password">Password:</label>
              <input type="password" name="password" id="id_password" required>
           </div>
           <button type="submit">Login</button>
        </form>
    </div>
</main>
{% endblock %}

projects/templates/base.html
<!--BASE-->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cyber_style.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                    <li><a href="{% url 'list_projects' %}">My Projects</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
    </footer>
    {% block script %}{% endblock %}
</body>
</html>

projects/templates/projects/create_project.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="bg-tron_road create-project">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
            <div>
                <label for="id_name">Name:</label>
                {{ form.name.errors }}
                {{ form.name }}
            </div>
            <div>
                <label for="id_description">Description:</label>
                {{ form.description.errors }}
                {{ form.description }}
            </div>
            <div>
                <label for="id_owner">Owner:</label>
                {{ form.owner }}
                {{ form.owner.errors }}
            </div>
            <button type="submit">Create</button>
        </form>
    </div>
</main>
{% endblock %}

projects/templates/projects/list_projects.html
{% extends 'base.html' %}
{% block content %}
    <title>"My Projects!"</title>
    <main>
        <div class="bg-timecube3 project-list">
            <h1>My Projects</h1>
            <nav>
                <p>
                    <a href="{% url 'create_project' %}">"Create a new project"</a>
                </p>
            </nav>
                        {% if projects %}
                <table>
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Number of tasks</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td><a href="{% url 'show_project' id=project.id %}">{{ project.name }}</a></td>
                                <td><p>Number of tasks: {{ project.tasks.all|length }}</p></td><!--Task to be filled in later-->
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
                <p>You are not assigned to any projects</p>
                <p>{{ message }}</p>
            {% endif %}
        </div>
    </main>
{% endblock %}

projects/templates/projects/project_details.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div class="bg-cyberpunk1 project-details">
        <h1>{{ project.name }}</h1>
        <p>{{ project.description }}</p>
        <h2>Tasks</h2>
        <p>
            <a href="{% url 'create_task' %}">"Create a new task"</a>
        </p>
        {% if project.tasks.all.exists %}
            <table>
                <tr>
                    <th>Name</th>
                    <th>Assignee</th>
                    <th>Start date</th>
                    <th>Due date</th>
                    <th>Is completed</th>
                </tr>
                {% for task in project.tasks.all %}
                    <tr>
                        <td>{{ task.name }}</td>
                        <td>{{ task.assignee.username }}</td>
                        <td>{{ task.start_date|date:"Y-m-d" }}</td>
                        <td>{{ task.due_date|date:"Y-m-d" }}</td>
                        <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                    </tr>
        {% endfor %}
            </table>
        {% else %}
            <p>This project has no tasks</p>
        {% endif %}
    </div>
</main>
{% endblock %}

tasks/templates/tasks/create_task.html
{% extends 'base.html' %}
{% block content %}
    <title>"Create a new task"</title>
    <main>
        <div class="bg-cosmic_way task-form">
            <h1>"Create a new task"</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

tasks/templates/tasks/my_tasks.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="bg-timeslip2 my-task-list">
        {% if tasks %}
            <h1>My Task</h1>
            <form action="{% url 'update_task_status' %}" method="post">
                {% csrf_token %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is Completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}

                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date|date:"Y-m-d" }}</td>
                                <td>{{ task.due_date|date:"Y-m-d" }}</td>
                                <td><input type="checkbox" name="task_completed_{{ task.id }}"
                            {% if task.is_completed %}checked{% endif %}>
                            <label for="task_completed_{{ task.id }}">{{ task.name }}</label></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <input type="submit" value="Update Tasks">
            </form>
    {% else %}
            <h1>
                <p>"You have no tasks."</p>
            </h1>
    {% endif %}
        </div>
    </main>
{% endblock %}

tracker/templates/base.html
<!--BASE-->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static "css/tracker.css" %}">
</head>
<body>
    <header>
        <!--Put the navigation in this spot-->
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                    <li><a href="{% url 'list_projects' %}">My Projects</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <!--footer content here-->
    </footer>
    {% block script %}{% endblock %}
</body>
</html>